// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CurrencySymbols
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("countriesFound")]
        public CountriesFound[] CountriesFound { get; set; }

        [JsonProperty("currency")]
        public Currency Currency { get; set; }
    }

    public partial class CountriesFound
    {
        [JsonProperty("country_name")]
        public string CountryName { get; set; }

        [JsonProperty("currency_name")]
        public CurrencyName CurrencyName { get; set; }

        [JsonProperty("currency_iso_code")]
        public Currency CurrencyIsoCode { get; set; }

        [JsonProperty("currency_number")]
        public long CurrencyNumber { get; set; }

        [JsonProperty("currency_mnr_unts")]
        public long CurrencyMnrUnts { get; set; }

        [JsonProperty("currency_symbol")]
        public CurrencySymbol CurrencySymbol { get; set; }
    }

    public enum Currency { Usd };

    public enum CurrencyName { UsDollar };

    public enum CurrencySymbol { Empty };
}
